#!/usr/bin/env python3
#
# The seven rules of a great Git commit message
# https://chris.beams.io/posts/git-commit/

from sys import argv, exit

commit_file = open(argv[1], 'r')

# Discard comments, i.e., all lines starting with #.
lines = []
for line in commit_file.readlines():
    if not line.startswith('#'):
        lines.append(line.rstrip('\n'))

subject = lines[0]
blank = ''
message = []

if len(lines) > 1:
    blank = lines[1]
    message = lines[2:]

# Our own rule: The commit message should start with the subject line.
if not len(subject) > 0:
    print("The commit message should start with a subject line")
    exit(1)

# Rule 1
if blank not in ['', '\n']:
    print("The subject and body are not separated by a blank line")
    exit(1)

# Rule 2
if len(subject) > 50:
    print("The subject line is too long")
    exit(1)

# Rule 3
first_word = subject.split(' ')[0]
if not first_word.istitle():
    print("The subject line is not capitalized")
    exit(1)

# Rule 4
if subject.endswith('.'):
    print("The subject line should not end with a period")
    exit(1)

# Rule 6
for line in message:
    line = line.rstrip('\n')
    if len(line) > 72:
        print("A line in body is too long")
        print("'{0}'".format(line))
        exit(1)
